Register user into database
CS372-Project/CS372Project pull request #15
Opened 2022-11-12 20:06 UTC by sarinalalria

2022-11-12 20:07 UTC, sarinalalria commented
I will fix the guest.html when the other pull request is fixed.

2022-11-12 20:17 UTC, Sinclair198 approved these changes
all good.

2022-11-12 21:18 UTC, YiShianLiu approved these changes

2022-11-14 20:35 UTC, nscheiber approved these changes

2022-11-14 20:49 UTC, zeshengchen requested changes

2022-11-14 20:49 UTC, zeshengchen commented on express-mongodb/signup-app.js
> +const url = 'mongodb+srv://gamequiz:gameQuizTeam@gamequiz.9o3my64.mongodb.net/test';
do not hard-coded username and password in the code. please use .env file and store them in this file.

2022-11-14 20:49 UTC, zeshengchen commented on express-mongodb/signup-app.js
> +const url = 'mongodb+srv://gamequiz:gameQuizTeam@gamequiz.9o3my64.mongodb.net/test';
Please use dotenv module.

2022-11-14 20:50 UTC, zeshengchen requested changes

2022-11-14 20:50 UTC, zeshengchen commented on express-mongodb/signup-app.js
> +return res.redirect('signup.html');
fix all indentation issue in the file

2022-11-14 20:51 UTC, zeshengchen requested changes

2022-11-14 20:51 UTC, zeshengchen commented on express-mongodb/package.json
> +    "body-parser": "^1.20.1",
As we discussed in the class, it prefers to use "-E" - extract version!

2022-11-14 20:51 UTC, zeshengchen commented on express-mongodb/signup-app.js
> +}).listen(3000)
put PORT into .env file as well!

2022-11-14 20:58 UTC, sarinalalria commented
Creating a new pull request to move folders, then I will fix the databse

2022-11-14 20:58 UTC, closed without merging