Create Dashboard
CS372-Project/CS372Project pull request #8
Opened 2022-10-13 21:15 UTC by YiShianLiu

2022-10-13 21:24 UTC, zeshengchen requested changes

2022-10-13 21:24 UTC, zeshengchen commented on HTML/dashboard.html
> +      <!-- jQuery CDN - Slim version (=without AJAX) -->
Indentation!

2022-10-13 21:35 UTC, zeshengchen approved these changes

2022-10-13 21:36 UTC, sarinalalria approved these changes
I have tested the code and it works well. I approve.

2022-10-13 22:08 UTC, Sinclair198 approved these changes
I ran the code I think it looks great. It's smooth and easy to navigate

2022-10-14 17:21 UTC, nscheiber approved these changes

2022-10-14 17:22 UTC, merged